### ISSUE TITLE
Breaks whole wordpress: Getting exceptions fixed one and now getting another one, please respond how this can be fixed?

### ISSUE THREAD

**Issue by mrimran** [Rareloop/wp-router#3]
Please see the details below about the exception. Before that I was getting another exception "Fatal error: Uncaught Error: Class 'Symfony\Component\HttpFoundation\Request' not found". Which I fixed by installing HttpFoundation composer package. Now this is something inside the code so please take a look at this. I hope if we get something like this working the life will be come easier :)

Fatal error: Uncaught TypeError: Argument 1 passed to Rareloop\Router\Router::match() must be an instance of Psr\Http\Message\ServerRequestInterface, instance of Symfony\Component\HttpFoundation\Request given, called in /var/www/ab-wp/htdocs/public/web/app/plugins/wp-router/src/Router.php on line 97 and defined in /var/www/ab-wp/htdocs/public/vendor/rareloop/router/src/Router.php:115 Stack trace: #0 /var/www/ab-wp/htdocs/public/web/app/plugins/wp-router/src/Router.php(97): Rareloop\Router\Router->match(Object(Symfony\Component\HttpFoundation\Request)) #1 /var/www/ab-wp/htdocs/public/web/app/plugins/wp-router/src/Router.php(54): Rareloop\WordPress\Router\Router::match(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/ab-wp/htdocs/public/web/wp/wp-includes/class-wp-hook.php(286): Rareloop\WordPress\Router\Router::processRequest('') #3 /var/www/ab-wp/htdocs/public/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /var/www/ab-wp/htdocs/public/web/wp/wp-includes/plugin.php(453): WP_H in /var/www/ab-wp/htdocs/public/vendor/rareloop/router/src/Router.php on line 115

**Comment by adamtomat** [comment]
Thanks for logging the issue (and PR).

Since releasing [v2 of our router](https://github.com/Rareloop/router) and of [lumberjack (still in beta)](https://github.com/Rareloop/lumberjack/tree/v2), we actually no longer use this wp-router package as it's [baked into lumberjack 2](https://github.com/Rareloop/lumberjack/tree/v2#router) out-of-the-box.

 I'll chat to the team here about what we can do.

**Comment by mrimran** [comment]
Thanks Adam for quick reply. Is v2 of your router is stable and will better
with bedrock?

I will give that a try tomorrow.

**Comment by mrimran** [comment]
@adamtomat lumberjack is not working as composer is throwing following exception
InvalidArgumentException]                        
  Could not find package rareloop/lumberjack-core.  
                                                    
  Did you mean this?                                
      rareloop/lumberjack-core                      

I've tried it many times also tried it with composer require --dev rareloop/lumberjack-core but that didn't work too.

**Comment by lchhieu** [comment]
How to mapping wp-router into wordpress? Thanks
